module.exports = [
  {
    date: '2022-04-01',
    name: 'Payday',
    source: 'Income',
    location: 'Checking Account',
    amount: 1000,
  },
  {
    date: '2022-04-01',
    name: 'Government Shakedown',
    source: 'Taxes',
    location: 'Savings Account',
    amount: -300,
  },
  {
    date: '2022-04-01',
    name: 'Acorns',
    source: 'Retirement',
    location: 'Checking Account',
    amount: -200,
  },
  {
    date: '2022-04-01',
    name: 'Rainy day',
    source: 'Savings',
    location: 'Checking Account',
    amount: -100,
  },
  {
    date: '2022-04-01',
    name: 'PayMyDues',
    source: 'Credit Card Payment',
    location: 'Checking Account',
    amount: -100,
  },
  {
    date: '2022-04-05',
    name: 'Residual Income',
    source: 'Birthday Money',
    location: 'Savings Account',
    amount: 20,
  },
  {
    date: '2022-04-05',
    name: 'Dunkin Donuts',
    source: 'Coffee',
    location: 'Checking Account',
    amount: -4,
  },
  {
    date: '2022-04-05',
    name: 'Verizon Fios',
    source: 'Internet',
    location: 'Credit Account',
    amount: -100,
  },
  {
    date: '2022-04-03',
    name: 'Bravo Supermarket',
    source: 'Groceries',
    location: 'Checking Account',
    amount: -76,
  },
  {
    date: '2022-04-03',
    name: 'Pet Land',
    source: 'Pet Food',
    location: 'Savings Account',
    amount: -15,
  },
];
